service: vus-backend-upload
disabledDeprecations:
    - CLI_OPTIONS_SCHEMA
useDotenv: true
plugins:
    - serverless-offline
    - serverless-dotenv-plugin
    - serverless-apigw-binary

custom:
    apigatewayBinary:
        types:
            - 'image/png'
            - 'image/jpeg'
            - 'image/jpg'

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: 20201221
    stage: dev
    region: ap-northeast-2
    apiGateway: { shouldStartNameWithService: true }
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - s3:PutObject
                      - s3:GetObject
                  Resource: 'arn:aws:s3:::'

functions:
    app:
        handler: handler.handler
        events:
            - http: ANY /
            - http: 'ANY {proxy+}'
